// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgZPtUHvN-ifmqXWECT-R8V-U4vI8qHrg',
    appId: '1:12171986026:web:99609175936384950c3613',
    messagingSenderId: '12171986026',
    projectId: 'andrei-flutter-ecommerce',
    authDomain: 'andrei-flutter-ecommerce.firebaseapp.com',
    storageBucket: 'andrei-flutter-ecommerce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdd65Nt5ESpjc1AlShaSNfIwoZHSemfbA',
    appId: '1:12171986026:android:7e22b584fb9b50050c3613',
    messagingSenderId: '12171986026',
    projectId: 'andrei-flutter-ecommerce',
    storageBucket: 'andrei-flutter-ecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbG92a17rnIZ2YmZHFsEkrkIJ8XLpELqw',
    appId: '1:12171986026:ios:936e70e57bc13d7c0c3613',
    messagingSenderId: '12171986026',
    projectId: 'andrei-flutter-ecommerce',
    storageBucket: 'andrei-flutter-ecommerce.appspot.com',
    iosClientId: '12171986026-cn7c32u0goc71ttci0hplpmbdv809q5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceFirebase',
  );
}
